/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Larissa
 */
public class CadastroJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroJFrame
     */
    public CadastroJFrame() {
        initComponents();
        setSize(1020, 630);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nometxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        telefonetxt = new javax.swing.JFormattedTextField();
        femininorb = new javax.swing.JRadioButton();
        masculinorb = new javax.swing.JRadioButton();
        usertxt = new javax.swing.JTextField();
        cpftxt = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        tipofuncionariorb = new javax.swing.JRadioButton();
        tipoadmrb = new javax.swing.JRadioButton();
        btncancelar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nometxt.setBackground(java.awt.SystemColor.control);
        nometxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt.setForeground(new java.awt.Color(0, 0, 0));
        nometxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxtActionPerformed(evt);
            }
        });
        getContentPane().add(nometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 62, 370, 30));

        emailtxt.setBackground(java.awt.SystemColor.control);
        emailtxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(0, 0, 0));
        emailtxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 380, 30));

        telefonetxt.setBackground(java.awt.SystemColor.control);
        telefonetxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        telefonetxt.setForeground(java.awt.SystemColor.controlText);
        telefonetxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("(##)#####-####"))));
        getContentPane().add(telefonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 180, 30));

        femininorb.setBackground(new java.awt.Color(0, 0, 0));
        femininorb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        femininorb.setForeground(new java.awt.Color(255, 255, 255));
        femininorb.setText("Feminino");
        femininorb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(femininorb, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 100, -1));

        masculinorb.setBackground(new java.awt.Color(0, 0, 0));
        masculinorb.setForeground(new java.awt.Color(255, 255, 255));
        masculinorb.setText("Masculino");
        masculinorb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        masculinorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinorbActionPerformed(evt);
            }
        });
        getContentPane().add(masculinorb, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 90, -1));

        usertxt.setBackground(java.awt.SystemColor.control);
        usertxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        usertxt.setForeground(new java.awt.Color(0, 0, 0));
        usertxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        getContentPane().add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 260, 30));

        cpftxt.setBackground(java.awt.SystemColor.control);
        cpftxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cpftxt.setForeground(new java.awt.Color(0, 0, 0));
        cpftxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cpftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpftxtActionPerformed(evt);
            }
        });
        getContentPane().add(cpftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 300, 30));

        jPasswordField1.setBackground(java.awt.SystemColor.control);
        jPasswordField1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 329, 240, 30));

        tipofuncionariorb.setBackground(new java.awt.Color(0, 0, 0));
        tipofuncionariorb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        tipofuncionariorb.setForeground(new java.awt.Color(255, 255, 255));
        tipofuncionariorb.setText(" Funcionário (permissão para realizar funções)");
        tipofuncionariorb.setToolTipText("");
        tipofuncionariorb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tipofuncionariorb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 290, 20));

        tipoadmrb.setBackground(new java.awt.Color(0, 0, 0));
        tipoadmrb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        tipoadmrb.setForeground(new java.awt.Color(255, 255, 255));
        tipoadmrb.setText("Administrador ( acesso total ao programa)");
        tipoadmrb.setToolTipText("");
        getContentPane().add(tipoadmrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 290, -1));

        btncancelar.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("CANCELAR");
        btncancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 73, 25));

        btnsalvar.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar.setText("SALVAR");
        btnsalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 73, 25));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Máximo de caracteres: 20");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 140, 15));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME DE USUÁRIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 272, 160, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Máximo de caracteres: 8");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nometxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void cpftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpftxtActionPerformed

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
         StartJFrame frm = new StartJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        StartJFrame frm = new StartJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void masculinorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinorbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinorbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JTextField cpftxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton femininorb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton masculinorb;
    private javax.swing.JTextField nometxt;
    private javax.swing.JFormattedTextField telefonetxt;
    private javax.swing.JRadioButton tipoadmrb;
    private javax.swing.JRadioButton tipofuncionariorb;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
