/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Larissa
 */
public class FinanceiroJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FinanceiroJFrame
     */
    public FinanceiroJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telefonetxt = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cpftxt2 = new javax.swing.JTextField();
        btnsalvar3 = new javax.swing.JButton();
        btnsalvar2 = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnsalvar1 = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btncancelar9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btncancelar10 = new javax.swing.JButton();
        btncancelar3 = new javax.swing.JButton();
        btnsalvar4 = new javax.swing.JButton();
        btnsalvar5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        btnsalvar6 = new javax.swing.JButton();
        btnsalvar7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        btnsalvar16 = new javax.swing.JButton();
        btnsalvar17 = new javax.swing.JButton();
        btnsalvar18 = new javax.swing.JButton();
        btnsalvar19 = new javax.swing.JButton();
        btncancelar8 = new javax.swing.JButton();
        btncancelar11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        btnsalvar20 = new javax.swing.JButton();
        btnsalvar21 = new javax.swing.JButton();
        btnsalvar22 = new javax.swing.JButton();
        btnsalvar23 = new javax.swing.JButton();
        bt = new javax.swing.JButton();
        btncancelar12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jTable1.setBackground(java.awt.SystemColor.control);
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF/CNPJ", "Nome do fornecedor", "Telefone", "E-mail", "Produto"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(50, 120, 670, 402);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BUSCAR POR NOME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(790, 150, 120, 22);

        jTextField2.setBackground(java.awt.SystemColor.control);
        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(750, 180, 190, 20);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF/CNPJ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(750, 210, 70, 22);

        jTextField1.setBackground(java.awt.SystemColor.control);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(820, 210, 120, 20);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOME DO FORNECEDOR");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 240, 140, 22);

        jTextField4.setBackground(java.awt.SystemColor.control);
        jTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(750, 270, 190, 20);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TELEFONE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(750, 300, 70, 22);

        telefonetxt.setBackground(java.awt.SystemColor.control);
        telefonetxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        telefonetxt.setForeground(java.awt.SystemColor.controlText);
        telefonetxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("(##)#####-####"))));
        telefonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonetxtActionPerformed(evt);
            }
        });
        jPanel1.add(telefonetxt);
        telefonetxt.setBounds(810, 300, 130, 20);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-MAIL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(750, 330, 50, 22);

        jTextField3.setBackground(java.awt.SystemColor.control);
        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(800, 330, 140, 20);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRODUTO");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(750, 360, 60, 22);

        cpftxt2.setBackground(java.awt.SystemColor.control);
        cpftxt2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cpftxt2.setForeground(new java.awt.Color(0, 0, 0));
        cpftxt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cpftxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpftxt2ActionPerformed(evt);
            }
        });
        jPanel1.add(cpftxt2);
        cpftxt2.setBounds(810, 360, 130, 20);

        btnsalvar3.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar3.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar3.setText("NOVO");
        btnsalvar3.setToolTipText("");
        btnsalvar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar3);
        btnsalvar3.setBounds(770, 420, 73, 25);

        btnsalvar2.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar2.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar2.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar2.setText("CONSULTAR");
        btnsalvar2.setToolTipText("");
        btnsalvar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar2);
        btnsalvar2.setBounds(850, 420, 73, 25);

        btnsalvar.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar.setText("ATUALIZAR");
        btnsalvar.setToolTipText("");
        btnsalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar);
        btnsalvar.setBounds(770, 450, 73, 25);

        btnsalvar1.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar1.setText("SALVAR");
        btnsalvar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar1);
        btnsalvar1.setBounds(850, 450, 73, 25);

        btncancelar.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("EXCLUIR");
        btncancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar);
        btncancelar.setBounds(770, 480, 73, 25);

        btncancelar9.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar9.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar9.setText("CANCELAR");
        btncancelar9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar9ActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar9);
        btncancelar9.setBounds(850, 480, 73, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/21.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 1010, 590);

        jTabbedPane1.addTab("Fornecedores", jPanel1);

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PERÍODO DE PAGAMENTO");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(50, 220, 150, 20);

        jFormattedTextField3.setBackground(java.awt.SystemColor.control);
        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel3.add(jFormattedTextField3);
        jFormattedTextField3.setBounds(80, 250, 103, 19);

        jFormattedTextField2.setBackground(java.awt.SystemColor.control);
        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel3.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(80, 280, 103, 19);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CATEGORIA");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(50, 340, 70, 20);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DE");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(60, 250, 20, 20);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("À");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(60, 280, 20, 20);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DE");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(60, 160, 20, 20);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("À");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(60, 190, 20, 20);

        jFormattedTextField4.setBackground(java.awt.SystemColor.control);
        jFormattedTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel3.add(jFormattedTextField4);
        jFormattedTextField4.setBounds(80, 160, 103, 19);

        jFormattedTextField5.setBackground(java.awt.SystemColor.control);
        jFormattedTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel3.add(jFormattedTextField5);
        jFormattedTextField5.setBounds(80, 190, 103, 19);

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PERÍODO DE VENCIMENTO");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(50, 130, 150, 20);

        jTextField5.setBackground(java.awt.SystemColor.control);
        jTextField5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(120, 370, 170, 20);

        jTable2.setBackground(java.awt.SystemColor.control);
        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vencimento", "Pagamento", "Fornecedor", "Categoria", "Descrição", "Valor total"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(320, 120, 630, 402);

        btncancelar10.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar10.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar10.setText("CANCELAR");
        btncancelar10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar10ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar10);
        btncancelar10.setBounds(220, 470, 73, 25);

        btncancelar3.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar3.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar3.setText("EXCLUIR");
        btncancelar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar3);
        btncancelar3.setBounds(140, 470, 73, 25);

        btnsalvar4.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar4.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar4.setText("ATUALIZAR");
        btnsalvar4.setToolTipText("");
        btnsalvar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar4);
        btnsalvar4.setBounds(220, 440, 73, 25);

        btnsalvar5.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar5.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar5.setText("SALVAR");
        btnsalvar5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar5ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar5);
        btnsalvar5.setBounds(60, 470, 73, 25);

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VALOR TOTAL ");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(50, 400, 90, 22);

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DESCRIÇÃO");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(50, 370, 80, 22);

        jFormattedTextField6.setBackground(java.awt.SystemColor.control);
        jFormattedTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel3.add(jFormattedTextField6);
        jFormattedTextField6.setBounds(140, 400, 150, 19);

        btnsalvar6.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar6.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar6.setText("NOVO");
        btnsalvar6.setToolTipText("");
        btnsalvar6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar6ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar6);
        btnsalvar6.setBounds(60, 440, 73, 25);

        btnsalvar7.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar7.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar7.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar7.setText("CONSULTAR");
        btnsalvar7.setToolTipText("");
        btnsalvar7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar7ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar7);
        btnsalvar7.setBounds(140, 440, 73, 25);

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("FORNECEDOR");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(50, 310, 80, 20);

        jTextField8.setBackground(java.awt.SystemColor.control);
        jTextField8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(51, 51, 51));
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField8);
        jTextField8.setBounds(130, 310, 160, 20);

        jTextField9.setBackground(java.awt.SystemColor.control);
        jTextField9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(51, 51, 51));
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9);
        jTextField9.setBounds(120, 340, 170, 20);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/22.png"))); // NOI18N
        jPanel3.add(jLabel20);
        jLabel20.setBounds(0, -20, 1004, 591);

        jTabbedPane1.addTab("Contas a pagar", jPanel3);

        jPanel4.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("FORMA DE PAGAMENTO");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(50, 310, 150, 20);

        jFormattedTextField11.setBackground(java.awt.SystemColor.control);
        jFormattedTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel4.add(jFormattedTextField11);
        jFormattedTextField11.setBounds(80, 190, 103, 19);

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DE");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(60, 160, 20, 20);

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("À");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(60, 190, 20, 20);

        jFormattedTextField10.setBackground(java.awt.SystemColor.control);
        jFormattedTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel4.add(jFormattedTextField10);
        jFormattedTextField10.setBounds(80, 160, 103, 19);

        jTable3.setBackground(java.awt.SystemColor.control);
        jTable3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Cód pedido", "Valor", "Forma de pagamento", "Data pagamento"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jPanel4.add(jScrollPane6);
        jScrollPane6.setBounds(320, 120, 630, 402);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PERÍODO DE VENCIMENTO");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(50, 130, 150, 20);

        jTextField10.setBackground(java.awt.SystemColor.control);
        jTextField10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(51, 51, 51));
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField10);
        jTextField10.setBounds(50, 340, 190, 20);

        jTextField11.setBackground(java.awt.SystemColor.control);
        jTextField11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(51, 51, 51));
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField11);
        jTextField11.setBounds(120, 250, 70, 20);

        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("VALOR");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(50, 280, 40, 20);

        jLabel30.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TIPO");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(50, 220, 30, 20);

        jFormattedTextField7.setBackground(java.awt.SystemColor.control);
        jFormattedTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel4.add(jFormattedTextField7);
        jFormattedTextField7.setBounds(100, 280, 110, 19);

        jLabel31.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("CÓD PEDIDO ");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(50, 250, 73, 20);

        jTextField12.setBackground(java.awt.SystemColor.control);
        jTextField12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(51, 51, 51));
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField12);
        jTextField12.setBounds(80, 220, 110, 20);

        btnsalvar16.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar16.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar16.setText("NOVO");
        btnsalvar16.setToolTipText("");
        btnsalvar16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar16ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar16);
        btnsalvar16.setBounds(60, 440, 73, 25);

        btnsalvar17.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar17.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar17.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar17.setText("CONSULTAR");
        btnsalvar17.setToolTipText("");
        btnsalvar17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar17ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar17);
        btnsalvar17.setBounds(140, 440, 73, 25);

        btnsalvar18.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar18.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar18.setText("ATUALIZAR");
        btnsalvar18.setToolTipText("");
        btnsalvar18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar18ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar18);
        btnsalvar18.setBounds(220, 440, 73, 25);

        btnsalvar19.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar19.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar19.setText("SALVAR");
        btnsalvar19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar19ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar19);
        btnsalvar19.setBounds(60, 470, 73, 25);

        btncancelar8.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar8.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar8.setText("EXCLUIR");
        btncancelar8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar8ActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar8);
        btncancelar8.setBounds(140, 470, 73, 25);

        btncancelar11.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar11.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar11.setText("CANCELAR");
        btncancelar11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar11ActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar11);
        btncancelar11.setBounds(220, 470, 73, 25);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/23.png"))); // NOI18N
        jPanel4.add(jLabel25);
        jLabel25.setBounds(0, -20, 1004, 591);

        jTabbedPane1.addTab("Contas a Receber", jPanel4);

        jPanel2.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SALDO PREVISTO");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(50, 250, 100, 20);

        jFormattedTextField8.setBackground(java.awt.SystemColor.control);
        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel2.add(jFormattedTextField8);
        jFormattedTextField8.setBounds(90, 120, 103, 19);

        jLabel28.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("SAÍDA REALIZADA");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(50, 280, 120, 20);

        jLabel29.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("DATA");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(50, 120, 40, 20);

        jTable4.setBackground(java.awt.SystemColor.control);
        jTable4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable4.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Recebido", "A pagar", "Pago", "Saldo previsto", "Saída realizada"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        jPanel2.add(jScrollPane7);
        jScrollPane7.setBounds(330, 110, 620, 402);

        jLabel32.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("RECEBIDO");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(50, 160, 60, 20);

        jLabel33.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("A PAGAR");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(50, 190, 60, 20);

        jLabel34.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("PAGO");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(50, 220, 40, 20);

        jFormattedTextField12.setBackground(java.awt.SystemColor.control);
        jFormattedTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField12);
        jFormattedTextField12.setBounds(110, 160, 160, 19);

        jFormattedTextField13.setBackground(java.awt.SystemColor.control);
        jFormattedTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField13);
        jFormattedTextField13.setBounds(110, 190, 160, 19);

        jFormattedTextField14.setBackground(java.awt.SystemColor.control);
        jFormattedTextField14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField14);
        jFormattedTextField14.setBounds(90, 220, 180, 19);

        jFormattedTextField15.setBackground(java.awt.SystemColor.control);
        jFormattedTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField15);
        jFormattedTextField15.setBounds(160, 250, 110, 19);

        jFormattedTextField16.setBackground(java.awt.SystemColor.control);
        jFormattedTextField16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField16);
        jFormattedTextField16.setBounds(160, 280, 110, 19);

        jLabel35.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("PESQUISAR");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(50, 320, 70, 20);

        jTextField13.setBackground(java.awt.SystemColor.control);
        jTextField13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(51, 51, 51));
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(120, 320, 150, 20);

        btnsalvar20.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar20.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar20.setText("NOVO");
        btnsalvar20.setToolTipText("");
        btnsalvar20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar20ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar20);
        btnsalvar20.setBounds(60, 440, 73, 25);

        btnsalvar21.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar21.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar21.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar21.setText("CONSULTAR");
        btnsalvar21.setToolTipText("");
        btnsalvar21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar21ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar21);
        btnsalvar21.setBounds(140, 440, 73, 25);

        btnsalvar22.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar22.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar22.setText("ATUALIZAR");
        btnsalvar22.setToolTipText("");
        btnsalvar22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar22ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar22);
        btnsalvar22.setBounds(220, 440, 73, 25);

        btnsalvar23.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar23.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar23.setText("SALVAR");
        btnsalvar23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar23ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar23);
        btnsalvar23.setBounds(60, 470, 73, 25);

        bt.setBackground(new java.awt.Color(51, 47, 45));
        bt.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt.setForeground(new java.awt.Color(255, 255, 255));
        bt.setText("EXCLUIR");
        bt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        jPanel2.add(bt);
        bt.setBounds(140, 470, 73, 25);

        btncancelar12.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar12.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar12.setText("CANCELAR");
        btncancelar12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar12ActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar12);
        btncancelar12.setBounds(220, 470, 73, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/25.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -30, 1004, 591);

        jTabbedPane1.addTab("Resumo financeiro", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1010, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar9ActionPerformed
        // TODO add your handling code here:
     MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar9ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar2ActionPerformed

    private void btnsalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar3ActionPerformed

    private void cpftxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpftxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpftxt2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void telefonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonetxtActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btncancelar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar10ActionPerformed
        // TODO add your handling code here:
         MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar10ActionPerformed

    private void btncancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar3ActionPerformed

    private void btnsalvar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar4ActionPerformed

    private void btnsalvar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar5ActionPerformed

    private void btnsalvar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar6ActionPerformed

    private void btnsalvar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void btnsalvar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar16ActionPerformed

    private void btnsalvar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar17ActionPerformed

    private void btnsalvar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar18ActionPerformed

    private void btnsalvar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar19ActionPerformed

    private void btncancelar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar8ActionPerformed

    private void btncancelar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar11ActionPerformed
        // TODO add your handling code here:
         MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar11ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void btnsalvar20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar20ActionPerformed

    private void btnsalvar21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar21ActionPerformed

    private void btnsalvar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar22ActionPerformed

    private void btnsalvar23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar23ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btActionPerformed

    private void btncancelar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar12ActionPerformed
        // TODO add your handling code here:
         MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceiroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceiroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceiroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceiroJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceiroJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar10;
    private javax.swing.JButton btncancelar11;
    private javax.swing.JButton btncancelar12;
    private javax.swing.JButton btncancelar3;
    private javax.swing.JButton btncancelar8;
    private javax.swing.JButton btncancelar9;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnsalvar1;
    private javax.swing.JButton btnsalvar16;
    private javax.swing.JButton btnsalvar17;
    private javax.swing.JButton btnsalvar18;
    private javax.swing.JButton btnsalvar19;
    private javax.swing.JButton btnsalvar2;
    private javax.swing.JButton btnsalvar20;
    private javax.swing.JButton btnsalvar21;
    private javax.swing.JButton btnsalvar22;
    private javax.swing.JButton btnsalvar23;
    private javax.swing.JButton btnsalvar3;
    private javax.swing.JButton btnsalvar4;
    private javax.swing.JButton btnsalvar5;
    private javax.swing.JButton btnsalvar6;
    private javax.swing.JButton btnsalvar7;
    private javax.swing.JTextField cpftxt2;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JFormattedTextField telefonetxt;
    // End of variables declaration//GEN-END:variables
}
