/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Larissa
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipallJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnsalvar3 = new javax.swing.JButton();
        btnsalvar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        btnsalvar1 = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btncancelar1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        btnsalvar4 = new javax.swing.JButton();
        btnsalvar17 = new javax.swing.JButton();
        btnsalvar18 = new javax.swing.JButton();
        btnsalvar19 = new javax.swing.JButton();
        btnsalvar20 = new javax.swing.JButton();
        btncancelar8 = new javax.swing.JButton();
        btncancelar2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        btnsalvar13 = new javax.swing.JButton();
        btnsalvar14 = new javax.swing.JButton();
        btnsalvar15 = new javax.swing.JButton();
        btnsalvar16 = new javax.swing.JButton();
        btncancelar6 = new javax.swing.JButton();
        btncancelar3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        telefonetxt = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        btnsalvar21 = new javax.swing.JButton();
        btnsalvar22 = new javax.swing.JButton();
        btnsalvar23 = new javax.swing.JButton();
        btnsalvar24 = new javax.swing.JButton();
        btncancelar10 = new javax.swing.JButton();
        btncancelar4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        tipoadmrb1 = new javax.swing.JRadioButton();
        tipoadmrb = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        telefonetxt1 = new javax.swing.JFormattedTextField();
        btnsalvar9 = new javax.swing.JButton();
        btnsalvar10 = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btnsalvar11 = new javax.swing.JButton();
        btnsalvar12 = new javax.swing.JButton();
        btncancelar5 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        btnsalvar3.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar3.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar3.setText("NOVO");
        btnsalvar3.setToolTipText("");
        btnsalvar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar3);
        btnsalvar3.setBounds(70, 460, 73, 25);

        btnsalvar2.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar2.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar2.setText("ATUALIZAR");
        btnsalvar2.setToolTipText("");
        btnsalvar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar2);
        btnsalvar2.setBounds(230, 460, 73, 25);

        jTextArea1.setBackground(java.awt.SystemColor.control);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 240, 230, 78);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALDO INICIAL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 120, 100, 22);

        jFormattedTextField7.setBackground(java.awt.SystemColor.control);
        jFormattedTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel1.add(jFormattedTextField7);
        jFormattedTextField7.setBounds(180, 390, 120, 19);

        jFormattedTextField5.setBackground(java.awt.SystemColor.control);
        jFormattedTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel1.add(jFormattedTextField5);
        jFormattedTextField5.setBounds(160, 120, 103, 19);

        jFormattedTextField4.setBackground(java.awt.SystemColor.control);
        jFormattedTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel1.add(jFormattedTextField4);
        jFormattedTextField4.setBounds(190, 360, 110, 19);

        jFormattedTextField2.setBackground(java.awt.SystemColor.control);
        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(110, 150, 103, 19);

        jFormattedTextField3.setBackground(java.awt.SystemColor.control);
        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        jPanel1.add(jFormattedTextField3);
        jFormattedTextField3.setBounds(110, 180, 103, 19);

        jFormattedTextField6.setBackground(java.awt.SystemColor.control);
        jFormattedTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel1.add(jFormattedTextField6);
        jFormattedTextField6.setBounds(160, 420, 140, 19);

        jTable1.setBackground(java.awt.SystemColor.control);
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Saldo incial", "Data", "Hora", "Descrição", "Entrada", "Saída", "Saldo final"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(340, 110, 600, 400);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("FECHAR CAIXA");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(230, 180, 100, 20);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("ABRIR CAIXA");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(230, 150, 100, 21);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SALDO FINAL");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 420, 80, 22);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ENTRADA DO CAIXA");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 360, 120, 22);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OBSERVAÇÕES");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 210, 100, 22);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SAÍDA DO CAIXA");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 390, 100, 22);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 150, 40, 20);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESCRIÇÃO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 330, 70, 22);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HORA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 180, 40, 20);

        btnsalvar.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar.setText("CONSULTAR");
        btnsalvar.setToolTipText("");
        btnsalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar);
        btnsalvar.setBounds(150, 460, 73, 25);

        btnsalvar1.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar1.setText("SALVAR");
        btnsalvar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalvar1);
        btnsalvar1.setBounds(70, 490, 73, 25);

        btnexcluir.setBackground(new java.awt.Color(51, 47, 45));
        btnexcluir.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnexcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnexcluir.setText("EXCLUIR");
        btnexcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnexcluir);
        btnexcluir.setBounds(150, 490, 73, 25);

        btncancelar1.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar1.setText("CANCELAR");
        btncancelar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar1);
        btncancelar1.setBounds(230, 490, 73, 25);

        jTextField3.setBackground(java.awt.SystemColor.control);
        jTextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(140, 330, 160, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -20, 1000, 590);

        jTabbedPane1.addTab("Abrir/fechar caixa", jPanel1);

        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOTAL");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 400, 40, 22);

        jTextField4.setBackground(java.awt.SystemColor.control);
        jTextField4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField4);
        jTextField4.setBounds(110, 370, 140, 20);

        jFormattedTextField8.setBackground(java.awt.SystemColor.control);
        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        jPanel2.add(jFormattedTextField8);
        jFormattedTextField8.setBounds(110, 200, 140, 20);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TEMPO");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 200, 40, 22);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("OBSERVAÇÕES");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(60, 260, 100, 22);

        jTable2.setBackground(java.awt.SystemColor.control);
        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° do pedido", "Tempo", "Atendente", "Observações", "Cliente", "Total"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(320, 110, 630, 403);

        jTextArea2.setBackground(java.awt.SystemColor.control);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(60, 290, 190, 70);

        jTextField6.setBackground(java.awt.SystemColor.control);
        jTextField6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField6);
        jTextField6.setBounds(60, 140, 190, 20);

        jTextField7.setBackground(java.awt.SystemColor.control);
        jTextField7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField7);
        jTextField7.setBounds(150, 170, 100, 20);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LOCALIZAR PRODUTO");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(60, 110, 130, 22);

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("N° DO PEDIDO");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(60, 170, 80, 22);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CLIENTE");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(60, 370, 50, 22);

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ATENDENTE");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(60, 230, 80, 22);

        jTextField8.setBackground(java.awt.SystemColor.control);
        jTextField8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextField8);
        jTextField8.setBounds(130, 230, 120, 20);

        jFormattedTextField9.setBackground(java.awt.SystemColor.control);
        jFormattedTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField9);
        jFormattedTextField9.setBounds(100, 400, 110, 19);

        btnsalvar4.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar4.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar4.setText("VISUALIZAR CONTA RESUMIDA");
        btnsalvar4.setToolTipText("");
        btnsalvar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar4);
        btnsalvar4.setBounds(80, 430, 210, 25);

        btnsalvar17.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar17.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar17.setText("NOVO");
        btnsalvar17.setToolTipText("");
        btnsalvar17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar17ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar17);
        btnsalvar17.setBounds(70, 460, 73, 25);

        btnsalvar18.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar18.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar18.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar18.setText("CONSULTAR");
        btnsalvar18.setToolTipText("");
        btnsalvar18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar18ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar18);
        btnsalvar18.setBounds(150, 460, 73, 25);

        btnsalvar19.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar19.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar19.setText("ATUALIZAR");
        btnsalvar19.setToolTipText("");
        btnsalvar19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar19ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar19);
        btnsalvar19.setBounds(230, 460, 73, 25);

        btnsalvar20.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar20.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar20.setText("SALVAR");
        btnsalvar20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar20ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar20);
        btnsalvar20.setBounds(70, 490, 73, 25);

        btncancelar8.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar8.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar8.setText("EXCLUIR");
        btncancelar8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar8ActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar8);
        btncancelar8.setBounds(150, 490, 73, 25);

        btncancelar2.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar2.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar2.setText("CANCELAR");
        btncancelar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar2ActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar2);
        btncancelar2.setBounds(230, 490, 73, 25);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TELAS PDV_1.png"))); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(0, -30, 1004, 600);

        jTabbedPane1.addTab("Pedidos no caixa", jPanel2);

        jPanel3.setLayout(null);

        jTextArea3.setBackground(java.awt.SystemColor.control);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(jTextArea3);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(50, 300, 210, 50);

        jTable3.setBackground(java.awt.SystemColor.control);
        jTable3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num", "Aberto em", "Duração", "Cliente", "Pedido", "Total(sem taxas)", "Total"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jPanel3.add(jScrollPane6);
        jScrollPane6.setBounds(330, 120, 610, 403);

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("N° PEDIDO");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(60, 150, 60, 22);

        jFormattedTextField10.setBackground(java.awt.SystemColor.control);
        jFormattedTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel3.add(jFormattedTextField10);
        jFormattedTextField10.setBounds(130, 180, 130, 20);

        jFormattedTextField11.setBackground(java.awt.SystemColor.control);
        jFormattedTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        jPanel3.add(jFormattedTextField11);
        jFormattedTextField11.setBounds(130, 210, 130, 19);

        jTextField10.setBackground(java.awt.SystemColor.control);
        jTextField10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10);
        jTextField10.setBounds(130, 150, 130, 20);

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("DURAÇÃO");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(60, 210, 60, 20);

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TOTAL ");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(50, 420, 50, 20);

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CLIENTE");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(60, 240, 50, 22);

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jCheckBox1.setForeground(java.awt.SystemColor.control);
        jCheckBox1.setText("Pagamento efetuado?");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(190, 410, 120, 21);

        jTextField11.setBackground(java.awt.SystemColor.control);
        jTextField11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jTextField11);
        jTextField11.setBounds(90, 420, 80, 20);

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ABERTO EM");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(60, 180, 80, 20);

        jFormattedTextField12.setBackground(java.awt.SystemColor.control);
        jFormattedTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel3.add(jFormattedTextField12);
        jFormattedTextField12.setBounds(120, 120, 140, 19);

        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("BUSCAR");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(60, 120, 50, 20);

        jLabel25.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("TOTAL (SEM TAXAS)");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(50, 360, 130, 20);

        jTextField12.setBackground(java.awt.SystemColor.control);
        jTextField12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jTextField12);
        jTextField12.setBounds(50, 390, 120, 20);

        jLabel27.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PEDIDO");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(60, 270, 100, 22);

        jTextField13.setBackground(java.awt.SystemColor.control);
        jTextField13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField13);
        jTextField13.setBounds(110, 240, 150, 20);

        btnsalvar13.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar13.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar13.setText("NOVO");
        btnsalvar13.setToolTipText("");
        btnsalvar13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar13ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar13);
        btnsalvar13.setBounds(70, 460, 73, 25);

        btnsalvar14.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar14.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar14.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar14.setText("CONSULTAR");
        btnsalvar14.setToolTipText("");
        btnsalvar14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar14ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar14);
        btnsalvar14.setBounds(150, 460, 73, 25);

        btnsalvar15.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar15.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar15.setText("ATUALIZAR");
        btnsalvar15.setToolTipText("");
        btnsalvar15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar15ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar15);
        btnsalvar15.setBounds(230, 460, 73, 25);

        btnsalvar16.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar16.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar16.setText("SALVAR");
        btnsalvar16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar16ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar16);
        btnsalvar16.setBounds(70, 490, 73, 25);

        btncancelar6.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar6.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar6.setText("EXCLUIR");
        btncancelar6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar6ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar6);
        btncancelar6.setBounds(150, 490, 73, 25);

        btncancelar3.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar3.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar3.setText("CANCELAR");
        btncancelar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar3);
        btncancelar3.setBounds(230, 490, 73, 25);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/11.png"))); // NOI18N
        jPanel3.add(jLabel26);
        jLabel26.setBounds(0, -20, 1004, 591);

        jTabbedPane1.addTab("Pedidos delivery", jPanel3);

        jPanel4.setLayout(null);

        jTable4.setBackground(java.awt.SystemColor.control);
        jTable4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "Endereço", "Num", "E-mail", "Qtd. de pedidos"
            }
        ));
        jScrollPane7.setViewportView(jTable4);

        jPanel4.add(jScrollPane7);
        jScrollPane7.setBounds(50, 120, 590, 400);

        jLabel28.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("BUSCAR");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(670, 160, 60, 22);

        jTextField9.setBackground(java.awt.SystemColor.control);
        jTextField9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(51, 51, 51));
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9);
        jTextField9.setBounds(730, 160, 220, 20);

        jLabel29.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("NOME");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(670, 190, 60, 22);

        jTextField5.setBackground(java.awt.SystemColor.control);
        jTextField5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField5);
        jTextField5.setBounds(710, 190, 240, 20);

        jLabel30.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TELEFONE");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(670, 220, 60, 22);

        telefonetxt.setBackground(java.awt.SystemColor.control);
        telefonetxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        telefonetxt.setForeground(java.awt.SystemColor.controlText);
        telefonetxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("(##)#####-####"))));
        jPanel4.add(telefonetxt);
        telefonetxt.setBounds(730, 220, 220, 20);

        jLabel31.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ENDEREÇO");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(670, 250, 60, 22);

        jTextField14.setBackground(java.awt.SystemColor.control);
        jTextField14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(51, 51, 51));
        jTextField14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField14);
        jTextField14.setBounds(740, 250, 210, 20);

        jLabel32.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("N° DO CLIENTE");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(670, 280, 100, 22);

        jTextField15.setBackground(java.awt.SystemColor.control);
        jTextField15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(51, 51, 51));
        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField15);
        jTextField15.setBounds(760, 280, 190, 20);

        jLabel33.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("E-MAIL");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(670, 310, 40, 22);

        jTextField16.setBackground(java.awt.SystemColor.control);
        jTextField16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(51, 51, 51));
        jTextField16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField16);
        jTextField16.setBounds(720, 310, 230, 20);

        jLabel34.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("QUANTIDADE DE PEDIDOS");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(670, 340, 150, 22);

        jTextField17.setBackground(java.awt.SystemColor.control);
        jTextField17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(51, 51, 51));
        jTextField17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField17);
        jTextField17.setBounds(820, 340, 130, 20);

        btnsalvar21.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar21.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar21.setText("NOVO");
        btnsalvar21.setToolTipText("");
        btnsalvar21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar21ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar21);
        btnsalvar21.setBounds(680, 410, 120, 30);

        btnsalvar22.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar22.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar22.setText("CONSULTAR");
        btnsalvar22.setToolTipText("");
        btnsalvar22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar22ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar22);
        btnsalvar22.setBounds(820, 410, 120, 30);

        btnsalvar23.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar23.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar23.setText("SALVAR");
        btnsalvar23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar23ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar23);
        btnsalvar23.setBounds(680, 450, 120, 25);

        btnsalvar24.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar24.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar24.setText("ATUALIZAR");
        btnsalvar24.setToolTipText("");
        btnsalvar24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar24ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar24);
        btnsalvar24.setBounds(820, 450, 120, 25);

        btncancelar10.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar10.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar10.setText("EXCLUIR");
        btncancelar10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar10ActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar10);
        btncancelar10.setBounds(680, 490, 120, 25);

        btncancelar4.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar4.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar4.setText("CANCELAR");
        btncancelar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar4ActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar4);
        btncancelar4.setBounds(820, 490, 120, 25);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/13.png"))); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(0, -20, 1004, 591);

        jTabbedPane1.addTab("Cliente", jPanel4);

        jPanel5.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("BUSCAR");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(50, 150, 50, 22);

        jTextField18.setBackground(java.awt.SystemColor.control);
        jTextField18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(51, 51, 51));
        jTextField18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField18);
        jTextField18.setBounds(110, 150, 220, 20);

        jTable5.setBackground(java.awt.SystemColor.control);
        jTable5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTable5.setForeground(new java.awt.Color(255, 255, 255));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód", "Nome", "Tipo", "Salário", "Telefone"
            }
        ));
        jScrollPane8.setViewportView(jTable5);

        jPanel5.add(jScrollPane8);
        jScrollPane8.setBounds(50, 180, 580, 340);

        jLabel37.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("CÓDIGO DO FUNCIONÁRIO");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(660, 180, 150, 20);

        jTextField19.setBackground(java.awt.SystemColor.control);
        jTextField19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(51, 51, 51));
        jTextField19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField19);
        jTextField19.setBounds(810, 180, 130, 20);

        jLabel38.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("NOME DE USUÁRIO");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(660, 210, 106, 20);

        jTextField20.setBackground(java.awt.SystemColor.control);
        jTextField20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(51, 51, 51));
        jTextField20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField20);
        jTextField20.setBounds(770, 210, 170, 20);

        jLabel39.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("TIPO");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(660, 240, 40, 20);

        tipoadmrb1.setBackground(new java.awt.Color(0, 0, 0));
        tipoadmrb1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        tipoadmrb1.setForeground(new java.awt.Color(255, 255, 255));
        tipoadmrb1.setText("Administrador (acesso total ao programa)");
        tipoadmrb1.setToolTipText("");
        jPanel5.add(tipoadmrb1);
        tipoadmrb1.setBounds(660, 270, 290, 22);

        tipoadmrb.setBackground(new java.awt.Color(0, 0, 0));
        tipoadmrb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        tipoadmrb.setForeground(new java.awt.Color(255, 255, 255));
        tipoadmrb.setText("Funcionário (permissão para realizar funções)");
        tipoadmrb.setToolTipText("");
        tipoadmrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoadmrbActionPerformed(evt);
            }
        });
        jPanel5.add(tipoadmrb);
        tipoadmrb.setBounds(660, 300, 290, 22);

        jLabel40.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("SALÁRIO");
        jPanel5.add(jLabel40);
        jLabel40.setBounds(660, 330, 60, 20);

        jFormattedTextField13.setBackground(java.awt.SystemColor.control);
        jFormattedTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel5.add(jFormattedTextField13);
        jFormattedTextField13.setBounds(720, 330, 230, 19);

        jLabel41.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("TELEFONE");
        jPanel5.add(jLabel41);
        jLabel41.setBounds(660, 360, 60, 20);

        telefonetxt1.setBackground(java.awt.SystemColor.control);
        telefonetxt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        telefonetxt1.setForeground(java.awt.SystemColor.controlText);
        telefonetxt1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("(##)#####-####"))));
        jPanel5.add(telefonetxt1);
        telefonetxt1.setBounds(720, 360, 230, 20);

        btnsalvar9.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar9.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar9.setText("NOVO");
        btnsalvar9.setToolTipText("");
        btnsalvar9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar9ActionPerformed(evt);
            }
        });
        jPanel5.add(btnsalvar9);
        btnsalvar9.setBounds(680, 410, 120, 30);

        btnsalvar10.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar10.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar10.setText("SALVAR");
        btnsalvar10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar10ActionPerformed(evt);
            }
        });
        jPanel5.add(btnsalvar10);
        btnsalvar10.setBounds(680, 450, 120, 25);

        btnc.setBackground(new java.awt.Color(51, 47, 45));
        btnc.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnc.setForeground(new java.awt.Color(255, 255, 255));
        btnc.setText("EXCLUIR");
        btnc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        jPanel5.add(btnc);
        btnc.setBounds(680, 490, 120, 25);

        btnsalvar11.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar11.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar11.setText("CONSULTAR");
        btnsalvar11.setToolTipText("");
        btnsalvar11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar11ActionPerformed(evt);
            }
        });
        jPanel5.add(btnsalvar11);
        btnsalvar11.setBounds(820, 410, 120, 30);

        btnsalvar12.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar12.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar12.setText("ATUALIZAR");
        btnsalvar12.setToolTipText("");
        btnsalvar12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar12ActionPerformed(evt);
            }
        });
        jPanel5.add(btnsalvar12);
        btnsalvar12.setBounds(820, 450, 120, 25);

        btncancelar5.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar5.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar5.setText("CANCELAR");
        btncancelar5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar5ActionPerformed(evt);
            }
        });
        jPanel5.add(btncancelar5);
        btncancelar5.setBounds(820, 490, 120, 25);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/14.png"))); // NOI18N
        jPanel5.add(jLabel35);
        jLabel35.setBounds(0, -10, 1010, 590);

        jTabbedPane1.addTab("Funcionários", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 591));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar3ActionPerformed

    private void btnsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar1ActionPerformed
        // TODO add your handling code here:
        MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnsalvar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void btnsalvar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar13ActionPerformed

    private void btnsalvar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar14ActionPerformed

    private void btnsalvar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar15ActionPerformed

    private void btnsalvar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar16ActionPerformed

    private void btncancelar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar6ActionPerformed

    private void btncancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar3ActionPerformed
        // TODO add your handling code here:
          MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar3ActionPerformed

    private void btnsalvar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar17ActionPerformed

    private void btnsalvar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar18ActionPerformed

    private void btnsalvar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar19ActionPerformed

    private void btnsalvar20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar20ActionPerformed

    private void btncancelar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar8ActionPerformed

    private void btncancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar2ActionPerformed
        // TODO add your handling code here:
          MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void tipoadmrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoadmrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoadmrbActionPerformed

    private void btnsalvar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar9ActionPerformed

    private void btnsalvar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar10ActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncActionPerformed

    private void btnsalvar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar11ActionPerformed

    private void btnsalvar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar12ActionPerformed

    private void btncancelar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar5ActionPerformed
        // TODO add your handling code here:
          MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar5ActionPerformed

    private void btnsalvar21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar21ActionPerformed

    private void btnsalvar22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar22ActionPerformed

    private void btnsalvar23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar23ActionPerformed

    private void btnsalvar24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar24ActionPerformed

    private void btncancelar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar10ActionPerformed

    private void btncancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar4ActionPerformed
        // TODO add your handling code here:
          MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnc;
    private javax.swing.JButton btncancelar1;
    private javax.swing.JButton btncancelar10;
    private javax.swing.JButton btncancelar2;
    private javax.swing.JButton btncancelar3;
    private javax.swing.JButton btncancelar4;
    private javax.swing.JButton btncancelar5;
    private javax.swing.JButton btncancelar6;
    private javax.swing.JButton btncancelar8;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnsalvar1;
    private javax.swing.JButton btnsalvar10;
    private javax.swing.JButton btnsalvar11;
    private javax.swing.JButton btnsalvar12;
    private javax.swing.JButton btnsalvar13;
    private javax.swing.JButton btnsalvar14;
    private javax.swing.JButton btnsalvar15;
    private javax.swing.JButton btnsalvar16;
    private javax.swing.JButton btnsalvar17;
    private javax.swing.JButton btnsalvar18;
    private javax.swing.JButton btnsalvar19;
    private javax.swing.JButton btnsalvar2;
    private javax.swing.JButton btnsalvar20;
    private javax.swing.JButton btnsalvar21;
    private javax.swing.JButton btnsalvar22;
    private javax.swing.JButton btnsalvar23;
    private javax.swing.JButton btnsalvar24;
    private javax.swing.JButton btnsalvar3;
    private javax.swing.JButton btnsalvar4;
    private javax.swing.JButton btnsalvar9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JFormattedTextField telefonetxt;
    private javax.swing.JFormattedTextField telefonetxt1;
    private javax.swing.JRadioButton tipoadmrb;
    private javax.swing.JRadioButton tipoadmrb1;
    // End of variables declaration//GEN-END:variables
}
