/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Larissa
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Itens
     */
    public Produtos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnbebidas = new javax.swing.JButton();
        btnentradas = new javax.swing.JButton();
        btnsobremesas = new javax.swing.JButton();
        btnpratos = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        nometxt12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        nometxt13 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nometxt14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        nometxt15 = new javax.swing.JTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        btnsalvar14 = new javax.swing.JButton();
        btnsalvar15 = new javax.swing.JButton();
        btnsalvar16 = new javax.swing.JButton();
        btncancelar4 = new javax.swing.JButton();
        btnsalvar17 = new javax.swing.JButton();
        btncancelar6 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nometxt6 = new javax.swing.JTextField();
        nometxt7 = new javax.swing.JTextField();
        nometxt8 = new javax.swing.JTextField();
        nometxt9 = new javax.swing.JTextField();
        nometxt10 = new javax.swing.JTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnsalvar10 = new javax.swing.JButton();
        btnsalvar11 = new javax.swing.JButton();
        btnsalvar12 = new javax.swing.JButton();
        btnsalvar13 = new javax.swing.JButton();
        btncancelar2 = new javax.swing.JButton();
        btncancelar7 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        nometxt11 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        nometxt2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nometxt4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nometxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nometxt3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nometxt1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        btnsalvar6 = new javax.swing.JButton();
        btnsalvar7 = new javax.swing.JButton();
        btnsalvar8 = new javax.swing.JButton();
        btnsalvar9 = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btncancelar8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        nometxt5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        btnbebidas.setBackground(new java.awt.Color(51, 47, 45));
        btnbebidas.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnbebidas.setForeground(new java.awt.Color(255, 255, 255));
        btnbebidas.setText("BEBIDAS");
        btnbebidas.setToolTipText("");
        btnbebidas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbebidasActionPerformed(evt);
            }
        });
        jPanel1.add(btnbebidas);
        btnbebidas.setBounds(540, 490, 180, 30);

        btnentradas.setBackground(new java.awt.Color(51, 47, 45));
        btnentradas.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnentradas.setForeground(new java.awt.Color(255, 255, 255));
        btnentradas.setText("ENTRADAS");
        btnentradas.setToolTipText("");
        btnentradas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentradasActionPerformed(evt);
            }
        });
        jPanel1.add(btnentradas);
        btnentradas.setBounds(240, 270, 180, 30);

        btnsobremesas.setBackground(new java.awt.Color(51, 47, 45));
        btnsobremesas.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsobremesas.setForeground(new java.awt.Color(255, 255, 255));
        btnsobremesas.setText("SOBREMESAS");
        btnsobremesas.setToolTipText("");
        btnsobremesas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsobremesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsobremesasActionPerformed(evt);
            }
        });
        jPanel1.add(btnsobremesas);
        btnsobremesas.setBounds(240, 490, 180, 30);

        btnpratos.setBackground(new java.awt.Color(51, 47, 45));
        btnpratos.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnpratos.setForeground(new java.awt.Color(255, 255, 255));
        btnpratos.setText("PRATOS PRINCIPAIS");
        btnpratos.setToolTipText("");
        btnpratos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpratosActionPerformed(evt);
            }
        });
        jPanel1.add(btnpratos);
        btnpratos.setBounds(540, 270, 180, 30);

        btnsair.setBackground(new java.awt.Color(51, 47, 45));
        btnsair.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsair.setForeground(new java.awt.Color(255, 255, 255));
        btnsair.setText("SAIR");
        btnsair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        jPanel1.add(btnsair);
        btnsair.setBounds(890, 510, 90, 28);

        btnvoltar.setBackground(new java.awt.Color(51, 47, 45));
        btnvoltar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnvoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnvoltar.setText("VOLTAR");
        btnvoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnvoltar);
        btnvoltar.setBounds(890, 470, 90, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cardapio_1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -30, 1004, 591);

        jTabbedPane1.addTab("Cardápio digital", jPanel1);

        jPanel2.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("BUSCAR");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(180, 120, 60, 20);

        nometxt12.setBackground(java.awt.SystemColor.control);
        nometxt12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt12.setForeground(new java.awt.Color(0, 0, 0));
        nometxt12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt12ActionPerformed(evt);
            }
        });
        jPanel2.add(nometxt12);
        nometxt12.setBounds(50, 150, 310, 20);

        jLabel28.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CÓDIGO DO SISTEMA");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(50, 180, 120, 20);

        nometxt13.setBackground(java.awt.SystemColor.control);
        nometxt13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt13.setForeground(new java.awt.Color(0, 0, 0));
        nometxt13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt13ActionPerformed(evt);
            }
        });
        jPanel2.add(nometxt13);
        nometxt13.setBounds(180, 180, 180, 20);

        jLabel29.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("NOME");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(50, 210, 40, 20);

        nometxt14.setBackground(java.awt.SystemColor.control);
        nometxt14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt14.setForeground(new java.awt.Color(0, 0, 0));
        nometxt14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt14ActionPerformed(evt);
            }
        });
        jPanel2.add(nometxt14);
        nometxt14.setBounds(90, 210, 270, 20);

        jLabel30.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CATEGORIA");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(50, 240, 70, 20);

        nometxt15.setBackground(java.awt.SystemColor.control);
        nometxt15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt15.setForeground(new java.awt.Color(0, 0, 0));
        nometxt15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt15ActionPerformed(evt);
            }
        });
        jPanel2.add(nometxt15);
        nometxt15.setBounds(130, 240, 230, 20);

        jFormattedTextField10.setBackground(java.awt.SystemColor.control);
        jFormattedTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField10);
        jFormattedTextField10.setBounds(160, 300, 200, 19);

        jLabel31.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(" PREÇO DE VENDA");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(50, 300, 110, 20);

        jLabel32.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(" PREÇO DE CUSTO");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(50, 270, 120, 20);

        jFormattedTextField11.setBackground(java.awt.SystemColor.control);
        jFormattedTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel2.add(jFormattedTextField11);
        jFormattedTextField11.setBounds(160, 270, 200, 19);

        jLabel33.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("MEDIDA");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(56, 330, 44, 22);

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("UN");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(110, 330, 50, 18);

        jRadioButton5.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("KG");
        jRadioButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jRadioButton5);
        jRadioButton5.setBounds(170, 330, 60, 18);

        jRadioButton6.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("LT");
        jRadioButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton6);
        jRadioButton6.setBounds(240, 330, 40, 18);

        btnsalvar14.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar14.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar14.setText("NOVO");
        btnsalvar14.setToolTipText("");
        btnsalvar14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar14ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar14);
        btnsalvar14.setBounds(70, 460, 73, 25);

        btnsalvar15.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar15.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar15.setText("SALVAR");
        btnsalvar15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar15ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar15);
        btnsalvar15.setBounds(70, 490, 73, 25);

        btnsalvar16.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar16.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar16.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar16.setText("CONSULTAR");
        btnsalvar16.setToolTipText("");
        btnsalvar16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar16ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar16);
        btnsalvar16.setBounds(150, 460, 73, 25);

        btncancelar4.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar4.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar4.setText("EXCLUIR");
        btncancelar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar4ActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar4);
        btncancelar4.setBounds(150, 490, 73, 25);

        btnsalvar17.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar17.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar17.setText("ATUALIZAR");
        btnsalvar17.setToolTipText("");
        btnsalvar17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar17ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar17);
        btnsalvar17.setBounds(230, 460, 73, 25);

        btncancelar6.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar6.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar6.setText("CANCELAR");
        btncancelar6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar6ActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar6);
        btncancelar6.setBounds(230, 490, 73, 25);

        jTable3.setBackground(java.awt.SystemColor.control);
        jTable3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable3.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cód do sistema", "Nome", "Categoria", "Preço de custo", "Preço de venda", "Medida"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(380, 120, 570, 402);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PRODUTOS_1.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, -30, 1000, 600);

        jTabbedPane1.addTab("Produtos", jPanel2);

        jPanel3.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VALOR COMPRA");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(50, 390, 100, 20);

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BUSCAR");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(180, 120, 60, 20);

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("NOME");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(50, 210, 40, 20);

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CATEGORIA");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(50, 240, 70, 20);

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PREÇO");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(50, 270, 50, 20);

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("MEDIDA");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(50, 300, 50, 20);

        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TIPO");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(50, 330, 40, 20);

        jLabel25.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("QUANTIDADE");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(50, 360, 74, 20);

        nometxt6.setBackground(java.awt.SystemColor.control);
        nometxt6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt6.setForeground(new java.awt.Color(0, 0, 0));
        nometxt6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt6ActionPerformed(evt);
            }
        });
        jPanel3.add(nometxt6);
        nometxt6.setBounds(50, 150, 310, 20);

        nometxt7.setBackground(java.awt.SystemColor.control);
        nometxt7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt7.setForeground(new java.awt.Color(0, 0, 0));
        nometxt7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt7ActionPerformed(evt);
            }
        });
        jPanel3.add(nometxt7);
        nometxt7.setBounds(90, 210, 270, 20);

        nometxt8.setBackground(java.awt.SystemColor.control);
        nometxt8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt8.setForeground(new java.awt.Color(0, 0, 0));
        nometxt8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt8ActionPerformed(evt);
            }
        });
        jPanel3.add(nometxt8);
        nometxt8.setBounds(130, 240, 230, 20);

        nometxt9.setBackground(java.awt.SystemColor.control);
        nometxt9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt9.setForeground(new java.awt.Color(0, 0, 0));
        nometxt9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt9ActionPerformed(evt);
            }
        });
        jPanel3.add(nometxt9);
        nometxt9.setBounds(80, 330, 270, 20);

        nometxt10.setBackground(java.awt.SystemColor.control);
        nometxt10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt10.setForeground(new java.awt.Color(0, 0, 0));
        nometxt10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt10ActionPerformed(evt);
            }
        });
        jPanel3.add(nometxt10);
        nometxt10.setBounds(130, 360, 220, 20);

        jFormattedTextField8.setBackground(java.awt.SystemColor.control);
        jFormattedTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel3.add(jFormattedTextField8);
        jFormattedTextField8.setBounds(100, 270, 260, 19);

        jFormattedTextField9.setBackground(java.awt.SystemColor.control);
        jFormattedTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel3.add(jFormattedTextField9);
        jFormattedTextField9.setBounds(150, 390, 200, 19);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("UN");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(100, 300, 50, 18);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("KG");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(160, 300, 60, 18);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("LT");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(230, 300, 40, 18);

        btnsalvar10.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar10.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar10.setText("NOVO");
        btnsalvar10.setToolTipText("");
        btnsalvar10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar10ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar10);
        btnsalvar10.setBounds(70, 460, 73, 25);

        btnsalvar11.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar11.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar11.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar11.setText("CONSULTAR");
        btnsalvar11.setToolTipText("");
        btnsalvar11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar11ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar11);
        btnsalvar11.setBounds(150, 460, 73, 25);

        btnsalvar12.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar12.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar12.setText("ATUALIZAR");
        btnsalvar12.setToolTipText("");
        btnsalvar12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar12ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar12);
        btnsalvar12.setBounds(230, 460, 73, 25);

        btnsalvar13.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar13.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar13.setText("SALVAR");
        btnsalvar13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar13ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalvar13);
        btnsalvar13.setBounds(70, 490, 73, 25);

        btncancelar2.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar2.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar2.setText("EXCLUIR");
        btncancelar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar2);
        btncancelar2.setBounds(150, 490, 73, 25);

        btncancelar7.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar7.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar7.setText("CANCELAR");
        btncancelar7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar7ActionPerformed(evt);
            }
        });
        jPanel3.add(btncancelar7);
        btncancelar7.setBounds(230, 490, 73, 25);

        jLabel26.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CÓDIGO DO SISTEMA");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(50, 180, 120, 20);

        nometxt11.setBackground(java.awt.SystemColor.control);
        nometxt11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt11.setForeground(new java.awt.Color(0, 0, 0));
        nometxt11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt11ActionPerformed(evt);
            }
        });
        jPanel3.add(nometxt11);
        nometxt11.setBounds(180, 180, 180, 20);

        jTable2.setBackground(java.awt.SystemColor.control);
        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cód do sistema", "Nome", "Categoria", "Preço", "Medida", "Qtd ", "Valor compra"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(380, 120, 570, 402);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/INSUMOS.png"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, -20, 1010, 590);

        jTabbedPane1.addTab("Insumos", jPanel3);

        jPanel4.setLayout(null);

        jTable1.setBackground(java.awt.SystemColor.control);
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cód do produto", "Modelo", "Cor", "Tamanho", "Qtd ", "Valor unitário", "Total"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(50, 110, 680, 402);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BUSCAR PRODUTO");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(790, 110, 120, 20);

        nometxt2.setBackground(java.awt.SystemColor.control);
        nometxt2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt2.setForeground(new java.awt.Color(0, 0, 0));
        nometxt2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt2ActionPerformed(evt);
            }
        });
        jPanel4.add(nometxt2);
        nometxt2.setBounds(750, 140, 210, 20);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MODELO");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(750, 200, 50, 20);

        nometxt4.setBackground(java.awt.SystemColor.control);
        nometxt4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt4.setForeground(new java.awt.Color(0, 0, 0));
        nometxt4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt4ActionPerformed(evt);
            }
        });
        jPanel4.add(nometxt4);
        nometxt4.setBounds(800, 200, 160, 20);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("COR");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(750, 230, 40, 20);

        nometxt.setBackground(java.awt.SystemColor.control);
        nometxt.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt.setForeground(new java.awt.Color(0, 0, 0));
        nometxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxtActionPerformed(evt);
            }
        });
        jPanel4.add(nometxt);
        nometxt.setBounds(780, 230, 180, 20);

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TAMANHO");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(750, 260, 70, 20);

        nometxt3.setBackground(java.awt.SystemColor.control);
        nometxt3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt3.setForeground(new java.awt.Color(0, 0, 0));
        nometxt3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt3ActionPerformed(evt);
            }
        });
        jPanel4.add(nometxt3);
        nometxt3.setBounds(820, 260, 140, 20);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("QUANTIDADE");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(750, 290, 80, 20);

        nometxt1.setBackground(java.awt.SystemColor.control);
        nometxt1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt1.setForeground(new java.awt.Color(0, 0, 0));
        nometxt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt1ActionPerformed(evt);
            }
        });
        jPanel4.add(nometxt1);
        nometxt1.setBounds(830, 290, 130, 20);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("VALOR UNITÁRIO");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(750, 320, 110, 20);

        jFormattedTextField6.setBackground(java.awt.SystemColor.control);
        jFormattedTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel4.add(jFormattedTextField6);
        jFormattedTextField6.setBounds(850, 320, 110, 19);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" TOTAL");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(750, 350, 50, 20);

        jFormattedTextField7.setBackground(java.awt.SystemColor.control);
        jFormattedTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        jPanel4.add(jFormattedTextField7);
        jFormattedTextField7.setBounds(800, 350, 160, 19);

        btnsalvar6.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar6.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar6.setText("NOVO");
        btnsalvar6.setToolTipText("");
        btnsalvar6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar6ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar6);
        btnsalvar6.setBounds(780, 400, 73, 25);

        btnsalvar7.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar7.setFont(new java.awt.Font("Agency FB", 1, 17)); // NOI18N
        btnsalvar7.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar7.setText("CONSULTAR");
        btnsalvar7.setToolTipText("");
        btnsalvar7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar7ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar7);
        btnsalvar7.setBounds(860, 400, 73, 25);

        btnsalvar8.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar8.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar8.setText("ATUALIZAR");
        btnsalvar8.setToolTipText("");
        btnsalvar8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar8ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar8);
        btnsalvar8.setBounds(780, 430, 73, 25);

        btnsalvar9.setBackground(new java.awt.Color(51, 47, 45));
        btnsalvar9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnsalvar9.setForeground(new java.awt.Color(255, 255, 255));
        btnsalvar9.setText("SALVAR");
        btnsalvar9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar9ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalvar9);
        btnsalvar9.setBounds(860, 430, 73, 25);

        btncancelar.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("EXCLUIR");
        btncancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar);
        btncancelar.setBounds(780, 460, 73, 25);

        btncancelar8.setBackground(new java.awt.Color(51, 47, 45));
        btncancelar8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btncancelar8.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar8.setText("CANCELAR");
        btncancelar8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancelar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar8ActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar8);
        btncancelar8.setBounds(860, 460, 73, 25);

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CÓD. PRODUTO");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(750, 170, 90, 20);

        nometxt5.setBackground(java.awt.SystemColor.control);
        nometxt5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nometxt5.setForeground(new java.awt.Color(0, 0, 0));
        nometxt5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nometxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxt5ActionPerformed(evt);
            }
        });
        jPanel4.add(nometxt5);
        nometxt5.setBounds(840, 170, 120, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque.png"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, -30, 1010, 591);

        jTabbedPane1.addTab("Estoque", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nometxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt5ActionPerformed

    private void btncancelar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar8ActionPerformed
        // TODO add your handling code here:
        MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar8ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalvar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar9ActionPerformed

    private void btnsalvar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar8ActionPerformed

    private void btnsalvar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar7ActionPerformed

    private void btnsalvar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar6ActionPerformed

    private void nometxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt1ActionPerformed

    private void nometxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt3ActionPerformed

    private void nometxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxtActionPerformed

    private void nometxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt4ActionPerformed

    private void nometxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt2ActionPerformed

    private void nometxt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt11ActionPerformed

    private void btncancelar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar7ActionPerformed
        // TODO add your handling code here:
        MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar7ActionPerformed

    private void btncancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar2ActionPerformed

    private void btnsalvar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar13ActionPerformed

    private void btnsalvar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar12ActionPerformed

    private void btnsalvar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar11ActionPerformed

    private void btnsalvar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar10ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void nometxt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt10ActionPerformed

    private void nometxt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt9ActionPerformed

    private void nometxt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt8ActionPerformed

    private void nometxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt7ActionPerformed

    private void nometxt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt6ActionPerformed

    private void btncancelar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar6ActionPerformed
        // TODO add your handling code here:
            MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncancelar6ActionPerformed

    private void btnsalvar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar17ActionPerformed

    private void btncancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar4ActionPerformed

    private void btnsalvar16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar16ActionPerformed

    private void btnsalvar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar15ActionPerformed

    private void btnsalvar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar14ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void nometxt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt15ActionPerformed

    private void nometxt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt14ActionPerformed

    private void nometxt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt13ActionPerformed

    private void nometxt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxt12ActionPerformed

    private void btnpratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpratosActionPerformed
        // TODO add your handling code here:
          CardapioJFrame frm = new CardapioJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpratosActionPerformed

    private void btnsobremesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsobremesasActionPerformed
        // TODO add your handling code here:
          CardapioJFrame frm = new CardapioJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsobremesasActionPerformed

    private void btnentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentradasActionPerformed
        // TODO add your handling code here:
      CardapioJFrame frm = new CardapioJFrame();
        frm.setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_btnentradasActionPerformed

    private void btnbebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbebidasActionPerformed
        // TODO add your handling code here:
          CardapioJFrame frm = new CardapioJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbebidasActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
        MenuJFrame frm = new MenuJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
        LoginJFrame frm = new LoginJFrame();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbebidas;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar2;
    private javax.swing.JButton btncancelar4;
    private javax.swing.JButton btncancelar6;
    private javax.swing.JButton btncancelar7;
    private javax.swing.JButton btncancelar8;
    private javax.swing.JButton btnentradas;
    private javax.swing.JButton btnpratos;
    private javax.swing.JButton btnsair;
    private javax.swing.JButton btnsalvar10;
    private javax.swing.JButton btnsalvar11;
    private javax.swing.JButton btnsalvar12;
    private javax.swing.JButton btnsalvar13;
    private javax.swing.JButton btnsalvar14;
    private javax.swing.JButton btnsalvar15;
    private javax.swing.JButton btnsalvar16;
    private javax.swing.JButton btnsalvar17;
    private javax.swing.JButton btnsalvar6;
    private javax.swing.JButton btnsalvar7;
    private javax.swing.JButton btnsalvar8;
    private javax.swing.JButton btnsalvar9;
    private javax.swing.JButton btnsobremesas;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField nometxt;
    private javax.swing.JTextField nometxt1;
    private javax.swing.JTextField nometxt10;
    private javax.swing.JTextField nometxt11;
    private javax.swing.JTextField nometxt12;
    private javax.swing.JTextField nometxt13;
    private javax.swing.JTextField nometxt14;
    private javax.swing.JTextField nometxt15;
    private javax.swing.JTextField nometxt2;
    private javax.swing.JTextField nometxt3;
    private javax.swing.JTextField nometxt4;
    private javax.swing.JTextField nometxt5;
    private javax.swing.JTextField nometxt6;
    private javax.swing.JTextField nometxt7;
    private javax.swing.JTextField nometxt8;
    private javax.swing.JTextField nometxt9;
    // End of variables declaration//GEN-END:variables
}
